# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
          
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      # Check out current repo
      - uses: actions/checkout@v2
      # Build the site
      - name: Jekyll build
        uses: docker://jekyll/jekyll:4.2.1
        with:
          args: jekyll build
      # Deploy it to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: github.event_name == 'push'
        with:
          deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./_site
