name: Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
          
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      # Check out current repo
      - name: Checkout current repository
        uses: actions/checkout@v2
      - name: List directory
        run: |
          pwd
          ls -a -l
      # Convert notebooks to Markdown posts
      - name: Convert Jupyter notebooks to Markdown blog posts
        uses: ptmerz/jupyter-minimal-mistakes@30107b348e7544c1d18e8bb0d41858f2dee8ecbc
      - name: List directory
        run: |
          pwd
          ls -a -l
          cat _posts/2021-12-*-jupyter-blogs.md 
      # Build and deploy the site
      - name: Build and deploy
        uses: EdricChan03/action-build-deploy-ghpages@v2.5.0
        with:
          skip_deploy: 'true'
          jekyll_build_opts: '--verbose'
        env:
          JEKYLL_ENV: 'production'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
